---
title: "Parallelisation"
output:
  rmarkdown::html_vignette:
    toc: true
description: |
  Parallel dataset queries
vignette: >
  %\VignetteIndexEntry{Parallelisation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, echo = FALSE, message =  FALSE, warning=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
withr:::defer({Sys.unsetenv('EDP_PROFILE')}, parent.frame(n=2))
```

# Implementation

* Implemented using [R future package](https://cran.r-project.org/web/packages/future/vignettes/future-1-overview.html).

# First read part of data

```{r start}
library(quartzbio.edp)
Sys.setenv(EDP_PROFILE = "vsim-dev_rw")


# contains > 3 millions of rows
ds <- Dataset(full_path = "quartzbio:Public:/TCGA/2.0.0-2018-mc3-v0.2.8/SomaticMutations-GRCh37")
ds$documents_count
# 3 603 497
COLS <- c("ensp", "variant_class")
df0 <- Dataset_query(ds, limit = 10000, meta = FALSE)




# fetch first 10000 rows
FILTER <- filters('variant_classification = "Silent"')
system.time(df1 <- Dataset_query(ds, fields = COLS, filters = FILTER, 
limit = 10000, meta = FALSE))

```

## Read all data

```{r par-1}
library(progressr)
library(future.apply)

# uncomment to see progress bars
#
#handlers(global = FALSE)
#handlers("txtprogressbar")

# sequential - no parallelisation
plan(sequential)
system.time(df <- Dataset_query(ds, fields = COLS, 
filters = FILTER, limit = 10000, meta = FALSE, all = TRUE, verbose = FALSE))

plan(multicore, workers = 4)
system.time(df.4 <- Dataset_query(ds, fields = COLS, filters = FILTER, limit = 10000, 
  meta = FALSE, all = TRUE, verbose = FALSE))

```

